using Acn.Fde.Practice.Api.Health;
using Acn.Fde.Practice.Api.Identity;
using Acn.Fde.Practice.Api.PracticeState;
using Acn.Fde.Practice.Contracts;
using Acn.Fde.Practice.Infrastructure.Repositories;
using CoreEx.HealthChecks;
using Microsoft.AspNetCore.DataProtection;
using OpenTelemetry;
using OpenTelemetry.Trace;
using System.Text.Json.Serialization;
using ZiggyCreatures.Caching.Fusion;

namespace Acn.Fde.Practice.Api;

public partial class Program
{
    private static void Main(string[] args)
    {
        // Create the web builder.
        var builder = WebApplication.CreateBuilder(args);

        // Keep the wire contract lossless: enum zero values and false bookmark
        // tombstones are meaningful, and every enum is camel-case on the wire.
        var jsonOptions = new JsonSerializerOptions(JsonDefaults.SerializerOptions)
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            MaxDepth = 16,
            RespectNullableAnnotations = true,
            UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
        };
        jsonOptions.Converters.Insert(0, new ReceiptJsonConverter());
        jsonOptions.Converters.Insert(0, new JsonStringEnumConverter(JsonNamingPolicy.CamelCase, allowIntegerValues: false));
        JsonDefaults.Configuration.SerializerOptions = jsonOptions;
        builder.Services.AddSingleton(jsonOptions);
        HttpNames.ErrorCodeName = "code";

        // Add CoreEx host settings.
        builder.AddHostSettings();

        // Add CoreEx services.
        builder.Services
            .AddPrecisionTimeProvider()
            .AddExecutionContext()
            .AddMvcWebApi()
            .AddHttpWebApi();

        // Trust only the short-lived identity token issued by the same-origin
        // Worker. Authorization uses its opaque subject; the GitHub account ID
        // remains recovery metadata only.
        builder.Services.AddIdentityAuthentication(builder.Configuration);

        // CoreEx issues no cookies or protected browser state; Better Auth owns that
        // boundary in the Worker. Keep any framework-internal protection keys
        // process-local so container restarts never imply durable filesystem state.
        builder.Services.AddDataProtection()
            .UseEphemeralDataProtectionProvider();

        // Dynamically register all [ScopedService] application services and infrastructure repositories (including those generated by CodeGen) by scanning each assembly. The AssemblyMarker types are stable anchors that always exist.
        builder.Services.AddDynamicServicesUsing(typeof(Acn.Fde.Practice.Application.AssemblyMarker).Assembly, typeof(Acn.Fde.Practice.Infrastructure.AssemblyMarker).Assembly);

        // Add the in-process cache. The service is a singleton in production, so no
        // distributed cache or Redis backplane is needed.
        builder.Services.AddMemoryCache();

        // Add and wire-up FusionCache as L1-only.
        builder.Services.AddFusionCache()
            .WithRegisteredMemoryCache()
            .WithSystemTextJsonSerializer(JsonDefaults.SerializerOptions);

        // Add CoreEx caching services.
        builder.Services
            .AddFusionHybridCache()                     // Adds the CoreEx.Caching.IHybridCache for FusionCache.
            .AddDefaultCacheKeyProvider();              // Adds the default CoreEx.Caching.ICacheKeyProvider.

        // Add the repository and related database services.
        builder.AddNpgsqlDataSource("Postgres");        // Adds the NpgsqlDataSource (using Aspire library).
        builder.Services
            .AddPostgresDatabase()                      // Adds the PostgresDatabase.
            .AddPostgresUnitOfWork()                    // Adds the PostgresUnitOfWork for the PostgresDatabase.
            .AddDbContext<PracticeDbContext>()       // Adds the standard EF DbContext.
            .AddEfDb<PracticeEfDb>();                // Adds the CoreEx extended EF service.

        // Separate process liveness, completed startup, and current dependency readiness.
        builder.Services.AddSingleton<LiveHealthCheck>();
        builder.Services.AddSingleton<StartupHealthCheck>();
        builder.Services.AddHealthChecks()
            .AddCheck<LiveHealthCheck>("process", tags: [nameof(HealthCheckTags.Live)])
            .AddCheck<StartupHealthCheck>("startup", tags: [nameof(HealthCheckTags.Startup)]);

        // Aspire's Npgsql integration registers an untagged, request-time database
        // check. Put unclassified dependency checks in readiness only.
        builder.Services.PostConfigureAllHealthChecks(registration =>
        {
            if (registration.Tags.Count == 0)
                registration.Tags.Add(nameof(HealthCheckTags.Ready));

            return false;
        });

        // Add the ASP.NET Core services.
        builder.Services.AddControllers();

        // Add the OpenAPI services.
        builder.Services.AddOpenApiDocument(s =>
        {
            s.Title = builder.Environment.ApplicationName;
            s.AddCoreExConfiguration();
        });

        // Add OpenTelemetry tracing.
        builder.WithCoreExTelemetry()
            .WithCoreExPostgresTelemetry()
            .UseOtlpExporter();

        // Build the application.
        var app = builder.Build();

        app.Lifetime.ApplicationStarted.Register(
            app.Services.GetRequiredService<StartupHealthCheck>().MarkStarted);

        // Configure the pipeline/middleware (order is important).
        app.UseCoreExExceptionHandler();
        app.UseAuthentication();
        app.UseExecutionContext(IdentityAuthentication.ConfigureExecutionContextAsync);
        app.UseAuthorization();
        app.UseMiddleware<PracticeStateRequestGuardMiddleware>();
        app.MapControllers();

        app.UseOpenApi();
        app.UseSwaggerUi();
        app.MapHealthChecks(/* detailedGroupConfigure: g => g.RequireAuthorization() */);   // Detailed endpoints expose diagnostics and must be secured; basic live/startup/ready checks stay anonymous for orchestrator probes.

        // Run the application.
        app.Run();
    }
}
