<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Acn.Fde.Practice.Contracts\Acn.Fde.Practice.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreEx.Data" />
    <PackageReference Include="CoreEx.Validation" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\contracts\question-recognition-manifest.json">
      <LogicalName>QuestionRecognitionManifest</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
