<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>acn-fde-practice-apphost</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Acn.Fde.Practice.Api\Acn.Fde.Practice.Api.csproj" />
    <ProjectReference Include="..\..\tools\Acn.Fde.Practice.Database\Acn.Fde.Practice.Database.csproj" />
  </ItemGroup>
</Project>
